-- phpMyAdmin SQL Dump
-- version 4.4.12
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Aug 09, 2017 at 09:09 AM
-- Server version: 5.6.25
-- PHP Version: 5.5.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bugwar`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE IF NOT EXISTS `admin` (
  `admin_id` int(11) NOT NULL,
  `uname` varchar(200) NOT NULL,
  `pwd` varchar(200) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`admin_id`, `uname`, `pwd`) VALUES
(1, 'sarath', 'apple'),
(2, 'admin', '0000');

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL,
  `category_name` varchar(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `category_name`) VALUES
(1, 'Batch 1'),
(2, 'Batch 2'),
(3, 'Batch 3');

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE IF NOT EXISTS `questions` (
  `id` int(11) NOT NULL,
  `question_name` text NOT NULL,
  `answer1` varchar(250) NOT NULL,
  `answer2` varchar(250) NOT NULL,
  `answer3` varchar(250) NOT NULL,
  `answer4` varchar(250) NOT NULL,
  `answer` varchar(250) NOT NULL,
  `category_id` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`id`, `question_name`, `answer1`, `answer2`, `answer3`, `answer4`, `answer`, `category_id`) VALUES
(1, 'The part of machine level instruction, which tells the central processor what has to be done, is_________?', 'Operation code', 'Address', 'Locator', 'None of the above', '1', 2),
(2, 'Which of the following refers to the associative memory?\r\n\r\n\r\n\r\n', 'the address of the data is generated by the CPU', 'the address of the data is supplied by the users', 'there is no need for an address i.e. the data is used as an address', 'the data are accessed sequentially', '3', 2),
(3, 'To avoid the race condition, the number of processes that may be simultaneously inside their critical section is_________\r\n\r\n\r\n', '8', '1', '16', '0', '2', 2),
(4, 'A system program that combines the separately compiled modules of a program into a form suitable for execution\r\n\r\n\r\n', 'Assembler', 'linking loader', 'cross compiler', 'load and go ', '2', 2),
(5, 'Process is defined as\r\n\r\n\r\n', 'program in High level language kept on disk', 'contents of main memory', 'a program in execution', 'a job in secondary memory', '3', 2),
(6, 'Which built-in method returns the index within the calling String object of the first occurrence of the specified value?\r\n', 'getIndex()', 'location()', ' indexOf()', 'None of the above.', '3', 3),
(7, 'Which built-in method returns the calling string value converted to upper case?\r\n', 'toUpperCase()', 'toUpper()', 'changeCase(case)', 'None of the above.', '1', 3),
(8, '6. How many objects can be created from an abstract class?\r\n\r\n', 'Zero', 'One', 'Two', 'As many as we want', '1', 2),
(9, 'Which of the following function of String object combines the text of two strings and returns a new string?\r\n\r\n', 'add()', 'merge()', 'concat()', ' append()', '3', 3),
(10, 'Copy constructor must receive its arguments by __________ .\r\n	', 'either pass-by-value or pass-by-reference', 'only pass-by-value', 'only pass-by-reference', 'only pass by address', '3', 2),
(11, 'Which of the following function of String object returns the characters in a string beginning at the specified location through the specified number of characters?\r\n \r\n', ' slice()', ' split()', ' substr()', ' search()', '3', 3),
(12, 'Which of the following implicitly creates a default constructor when the programmer does not explicitly define at least one constructor for a class?\r\n\r\n', 'Preprocessor', 'Linker', 'Loader', 'Compiler', '3', 2),
(13, 'Which of the following function of String object returns a string representing the specified object?\r\n', ' toLocaleUpperCase()', 'toUpperCase()', 'toString()', 'substring()', '3', 3),
(14, 'For automatic objects, constructors and destructors are called each time the objects__________\r\n	', 'enter and leave scope', 'inherit parent class', 'are constructed', 'are destroyed', '1', 2),
(15, 'Page stealing\r\n\r\n\r\n\r\n', 'is a sign of an efficient system', 'is taking page frames from other working sets', 'should be the tuning goal', 'is taking larger disk spaces for pages paged out', '2', 3),
(16, 'Which of the following approach is adapted by C++?\r\n	', 'Top-down', 'Bottom-up', 'Right-left', 'Left-right', '2', 2),
(17, '7. 	In MS-DOS 5.0, which is the number that acts as a code to uniquely identify the software product?', 'MS', 'DOS', 'MS DOS', '5.0', '3', 3),
(18, 'Which of the following selector matches the name of any element type?\n', 'The Type Selector', 'The Universal Selector', 'The Descendant Selector', 'The Class Selector', '2', 2),
(19, 'Bug means\r\n\r\n\r\n', 'A logical error in a program', 'A difficult syntax error in a program', 'Documenting programs using an efficient documentation tool', 'All of the above', '1', 3),
(20, '1.Which of the following cannot be checked in a switch-case statement?\n', 'Character', 'Integer', 'Float', 'enum', '3', 1),
(21, '12Which of the following selector selects all paragraph elements whose lang attribute \r\ncontains values that are exactly "fr", or begin with "fr-"?\r\nA -\r\nB - \r\nC - \r\nD - \r\n', ' p[lang]', 'p[lang="fr"]', 'p[lang~="fr"]', 'p[lang|="fr"]', '3', 2),
(23, 'Which of the following is correct about Hex Code format of CSS colors?\r\n', 'The first two digits(RR) represent a red value.', 'The next two are a green value(GG).', 'The last are the blue value(BB).', 'All of the above.', '3', 2),
(24, 'Memory management is :\r\n', 'not used in modern operating system', 'replaced with virtual memory on current systems', 'not used on multiprogramming systems', 'critical for even the simplest operating systems', '3', 3),
(25, '- Which of the following is correct about Browser Safe Colors?\r\n', 'These are 216 colors which are supposed to be most safe and computer independent colors.', 'These colors vary from hexa code 000000 to FFFFFF.', 'These colors are safe to use because they ensure that all computers would display the colors correctly when running a 256 color palette.', 'All of the above.', '3', 2),
(26, 'What is the name of the operating system for the laptop computer called MacLite?\r\n\r\n', 'Windows', 'DOS', 'MS-DOS', 'OZ', '3', 3),
(27, 'Which of the following property is used to underline, overline, and strikethrough text?\r\n\r\n', 'text-indent', 'text-align', 'text-decoration', ' text-transform', '3', 2),
(28, '\r\n Which of the following functions are performed by a constructor?\r\n	', 'Construct a new class', 'Construct a new object', 'construct a new function', 'Initialize objects', '3', 3),
(29, 'Which of the following property is used to set the text shadow around a text?\r\n\r\n', 'white-space', 'text-shadow', 'text-decoration', 'text-transform', '2', 2),
(30, ' The library function used to reverse a string is\r\n', 'strstr()', '  strrev()', 'revstr()', ' strreverse()', '2', 1),
(31, 'A function with the same name as the class, but preceded with a tilde character (~) is called __________ of that class.\r\n	', 'constructor 		', 'destructor', 'function', 'object', '2', 3),
(32, 'Which of the following property of a table element allows browsers to speed up layout of a table by using the first width properties it comes across for the rest of a column rather than having to load the whole table before rendering it?\r\n', ':table-layout', ':border-spacing', 'caption-side', ':empty-cells', '1', 2),
(33, 'public class Test { }\r\nWhat is the prototype of the default constructor?\r\n             .	\r\n', 'Test( )', 'Test(void)', '	public Test( )', 'public Test(void)', '3', 3),
(34, 'The keyword used to transfer control from a function back to the calling function is\r\n', 'switch', 'goto', 'go back', 'return', '3', 1),
(35, 'Which of the following property changes the style of right border?\r\n', 'border-bottom-style', 'border-top-style', 'border-left-style', 'border-right-style', '3', 2),
(36, 'Which class does not override the equals() and hashCode() methods, inheriting them directly from class Object?\r\n', 'java.lang.String', 'java.lang.Double', 'java.lang.StringBuffer', 'java.lang.Character', '3', 3),
(37, 'The library function used to find the last occurrence of a character in a string is\r\n', 'strnstr()', 'laststr()', 'strrchr()', 'strstr()', '3', 1),
(38, 'Which of the following property changes the width of right border?\r\n', 'border-bottom-width', 'border-top-width', 'border-left-width', ':border-right-width', '1', 2),
(39, 'What is the most restrictive access modifier that will allow members of one class to have access to members of another class in the same package?\r\n		\r\n', 'public', 'abstract', 'protected', 'default access', '3', 3),
(40, 'Which of the following attribute triggers event when an element is invalid?\r\n', ' onhaschange', ' oninput', ' oninvalid', 'onvalidate', '3', 1),
(41, '. Which is a valid declaration within an interface?\r\n	', 'public static short stop = 23;', 'protected short stop = 23;', 'transient short stop = 23;', 'final void madness(short stop);', '1', 3),
(42, 'Which of the following property serves as shorthand for the padding properties?\r\nA - \r\nB - \r\nC -\r\nD - \r\n', 'padding', 'padding-top', ' padding-left', 'padding-right', '3', 2),
(43, 'Which collection class allows you to grow or shrink its size and provides indexed access to its elements, but whose methods are not synchronized?\r\n	', 'java.util.HashSet', 'java.util.LinkedHashSet', 'java.util.List', 'java.util.ArrayList', '3', 3),
(44, '.Which of the following are input type attribute in html5?\r\n1) search\r\n2) datetime\r\n3) week\r\n4) color\r\n5) track\r\n6) placeholder\r\n', ' 1,2,3,4,6', '1,2,3,4,5', ' 2,3,4,5,6', '1,3,4,5,6', '1', 1),
(45, 'Which of the following will not directly cause a thread to stop?\r\n	', 'notify()', 'wait()', 'InputStream access', 'sleep()', '1', 3),
(46, 'One should never combine the &quot;start&quot; and &quot;type&quot; option ?\r\n', 'True', 'Sometimes True, sometimes False', 'False', 'neither true nor false', '3', 1),
(47, '. Which constructs an anonymous inner class instance?\r\n	', 'Runnable r = new Runnable() { };', 'Runnable r = new Runnable(public void run() { });', 'Runnable r = new Runnable { public void run(){}};', 'System.out.println(new Runnable() {public void run() { }', '3', 3),
(48, 'Use what to prevent confusion on numbers higher than 9 with hexadecimal colors ?\r\n', '#', '! ', '%', '~', '1', 1),
(49, 'Which interface does java.util.Hashtable implement?\r\n	', 'Java.util.Map', 'Java.util.List', 'Java.util.HashTable', 'Java.util.Collection', '1', 3),
(50, 'Which two meta tags have special relevance for search engines ?\r\n', 'Description and Keywords', 'Description and Name', ' Cookies and Keywords', 'cookies and names', '1', 1),
(51, 'Which of the following are(is) Language Processor(s)\r\n ', 'assembles', ' compilers', 'interpreters', 'All of the above', '3', 1),
(52, 'Fragmentation of the file system\r\n', 'occurs only if the file system is used improperly', 'can always be prevented', ' can be temporarily removed by compaction', 'is a characteristic of all file systems', '3', 1),
(53, 'Which two files are used during operation of the DBMS?\r\n', 'query language and utilities', ' data manipulation language and query language', 'data dictionary and transaction log', 'data dictionary and query language', '3', 1),
(54, 'Which of the following is not a relational database?\r\n', ' dBASE IV', '4th Dimension', 'FoxPro', 'Reflex', '3', 1),
(55, '15.The highest level in the hierarchy of data organization is called\r\n', 'data bank', 'database', ' data file', 'data record', '2', 1),
(56, '.In SQL, which command(s) is(are) used to enable/disable all triggers on a table?\r\n', ' ALTER TRIGGERS', ' ALTER TABLE', 'MODIFY TRIGGERS IN TABLE', 'All of the above', '2', 1),
(57, 'The PROJECT command will create new table that has\r\n', 'more fields than the original table', 'more rows than the original table', 'all the fields of master table', ' None of the above', '3', 1),
(58, 'Sophisticated report generators can\r\n', ' print row-oriented reports', 'perform arithmetic operations', 'selectively retrieve and print portions of a list', 'All of the above', '3', 1),
(59, '.What is the language used by most of the DBMSs for helping their users to\r\naccess data?\r\n', 'High level language', 'Query language', ' SQL', '4GL', '2', 1),
(60, 'In SQL, which command is used to make permanent changes made by\r\nstatements issue since the beginning of a transaction?\r\n \r\n', 'ZIP', 'PACK', 'COMMIT', 'SAVE', '3', 1),
(61, 'Name the access modifier which when used with a method, makes it available to all the\r\nclasses in the same package and to all the subclasses of the class.\r\n', 'public', ' protected', 'private', 'default', '2', 1);

-- --------------------------------------------------------

--
-- Table structure for table `scores`
--

CREATE TABLE IF NOT EXISTS `scores` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `right_answer` int(11) NOT NULL,
  `wrong_answer` int(11) NOT NULL,
  `unanswered` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(60) NOT NULL,
  `password` varchar(60) NOT NULL DEFAULT '1270',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` varchar(70) NOT NULL,
  `pno` varchar(30) DEFAULT NULL,
  `dept` varchar(30) DEFAULT NULL,
  `college` varchar(50) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `created`, `uuid`, `pno`, `dept`, `college`) VALUES
(8, 'sarath kumar', 'sarath674@gmail.com', '1270', '2017-08-07 02:04:18', '', '9042964665', 'IT', 'velammal engineering college'),
(9, 'mithra shree', 'mithra@gmail.com', '1270', '2017-08-07 17:25:07', '', '9042964665', 'IT', 'velammal engineering college'),
(10, 'dinesh', 'drjdinu@gmail.com', '1270', '2017-08-07 17:25:57', '', '9042964665', 'ECE', 'velammal engineering college'),
(11, 'sonthsh', 'sonthosh@gmail.com', '1270', '2017-08-07 17:26:23', '', '9042964665', 'EIE', 'velammal engineering college'),
(12, 'sathish', 'shawnnthunder@gmail.com', '1270', '2017-08-07 17:27:03', '', '9042964665', 'MECH', 'VEC'),
(13, 'pradeep', 'pradeep@gmail.com', '1270', '2017-08-07 19:55:43', '', '9042964665', 'CSE', 'Veltech Engineering college'),
(14, 'manju', 'manju@gmail.com', '1270', '2017-08-08 09:23:10', '', '9042964665', 'CSE', 'velammal engineering college'),
(15, 'sarath kumar', 'saraths300697@gmail.com', '1270', '2017-08-08 11:29:03', '', '9042964665', 'IT', 'vec');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`admin_id`);

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `scores`
--
ALTER TABLE `scores`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`,`category_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`),
  ADD KEY `login` (`password`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `admin_id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `questions`
--
ALTER TABLE `questions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=62;
--
-- AUTO_INCREMENT for table `scores`
--
ALTER TABLE `scores`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=9;
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=17;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
